name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    env:
      MONGO_URL: ${{secrets.MONGO_URL}}
      ELV_PRIVKEY: ${{secrets.ELV_PRIVKEY}}
      ELV_URL: ${{secrets.ELV_URL}}
      ELV_LIBID: ${{secrets.ELV_LIBID}}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.16]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: npx prettier --write .
      - run: npx eslint .
